<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>asge</AssemblyName>
    <RootNamespace>ASGE</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>ASGE</AssemblyTitle>
    <AssemblyDescription>Azure Storage GZip Encoding Tool</AssemblyDescription>
    <AssemblyProduct>ASGE</AssemblyProduct>
    <AssemblyCopyright>Copyright © Stefan Gordon 2016</AssemblyCopyright>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Options.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Utility.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Options_old.cs" />
    <Compile Remove="Program_old.cs" />
    <Compile Remove="Utility_old.cs" />
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.1" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
  </ItemGroup>

</Project>